language: node_js
services:
  - redis-server
addons:
  apt:
    packages:
      - redis-server
language: node_js
node_js:
- '7'
before_install:
- npm install jsdoc -g
install:
- npm install
script:
- npm run build
- npm run doc
- npm run test
